---
# tasks file for hswong3i.composer

- name: download composer installer
  get_url:
    url: "{{ composer_url }}"
    dest: "{{ composer_installer }}"
    checksum: "{{ composer_checksum }}"
  tags: hswong3i.composer

- name: install composer with installer
  shell: |
    php {{ composer_installer }} --install-dir={{ composer_install_dir }} --filename=composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: hswong3i.composer

- name: composer self-update
  shell: |
    composer self-update
  register: composer_self_update_result
  changed_when: composer_self_update_result.rc != 0
  tags: hswong3i.composer

- name: prepare files
  file:
    path: "{{ item.path }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { path: "/root/.composer", owner: "root", group: "root", mode: "0755", state: "directory" }
  tags: hswong3i.composer

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/profile.d/composer.sh.j2", dest: "/etc/profile.d/composer.sh", owner: "root", group: "root", mode: "0644" }
    - { src: "root/.composer/auth.json.j2", dest: "/root/.composer/auth.json", owner: "root", group: "root", mode: "0644" }
  tags: hswong3i.composer

- name: composer global require
  shell: |
    composer global require {{ item }}
  with_items: "{{ composer_global_require }}"
  register: composer_global_require_result
  changed_when: composer_global_require_result.rc != 0
  tags: hswong3i.composer

- name: composer global update
  shell: |
    composer global update
  when: composer_global_require | length > 0
  register: composer_global_update_result
  changed_when: composer_global_update_result.rc != 0
  tags: hswong3i.composer
