---
# tasks file for hswong3i.composer

- name: download composer installer
  get_url:
    url: "{{ composer_url }}"
    dest: "{{ composer_installer }}"
    checksum: "{{ composer_checksum }}"
  tags: hswong3i.composer

- name: install with composer installer
  shell: |
    php {{ composer_installer }} --install-dir={{ composer_install_dir }} --filename=composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: hswong3i.composer

- name: composer self-update
  composer:
    command: "self-update"
  tags: hswong3i.composer
