---
# tasks file for hswong3i.composer

- name: download composer installer
  get_url:
    url: "{{ composer_url }}"
    dest: "{{ composer_installer }}"
    checksum: "{{ composer_checksum }}"
  tags: hswong3i.composer

- name: install composer with installer
  shell: |
    php {{ composer_installer }} --install-dir={{ composer_install_dir }} --filename=composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: hswong3i.composer

- name: composer self-update
  shell: |
    composer self-update
  register: composer_self_update_result
  changed_when: composer_self_update_result.rc != 0
  tags: hswong3i.composer
