---
# tasks file for hswong3i.composer

- name: download composer installer
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    checksum: "{{ item.checksum }}"
  with_items:
    - { url: "{{ composer_installer_url }}", dest: "{{ composer_installer_dest }}", checksum: "{{ composer_installer_checksum }}" }
  tags: hswong3i.composer

- name: install composer with installer
  shell: |
    php {{ composer_installer_dest }} --install-dir={{ composer_install_dir }} --filename=composer
  args:
    creates: "{{ composer_install_dir }}/composer"
  tags: hswong3i.composer

- name: composer self-update
  shell: |
    composer self-update --no-interaction
  register: composer_self_update_result
  changed_when: "'You are already using composer' not in composer_self_update_result.stderr"
  tags: hswong3i.composer

- name: prepare files
  file:
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
    state: "{{ item.state }}"
  with_items:
    - { dest: "{{ composer_home }}", owner: "root", group: "root", mode: "0755", state: "directory" }
  tags: hswong3i.composer

- name: copy templates
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner }}"
    group: "{{ item.group }}"
    mode: "{{ item.mode }}"
  with_items:
    - { src: "etc/profile.d/composer.sh.j2", dest: "/etc/profile.d/composer.sh", owner: "root", group: "root", mode: "0644" }
    - { src: "usr/share/composer/auth.json.j2", dest: "{{ composer_home}}/auth.json", owner: "root", group: "root", mode: "0644" }
  tags: hswong3i.composer

- name: composer global init
  shell: |
    COMPOSER_HOME={{ composer_home }} composer global init --no-interaction
  args:
    creates: "{{ composer_home }}/composer.json"
  register: composer_global_init_result
  changed_when: composer_global_init_result.rc != 0
  tags: hswong3i.composer

- name: composer global config
  shell: |
    COMPOSER_HOME={{ composer_home }} composer global config {{ item.key }} {{ item.value }} --no-interaction
  with_items: "{{ composer_global_config }}"
  register: composer_global_config_result
  changed_when: composer_global_config_result.rc != 0
  tags: hswong3i.composer

- name: composer global
  shell: |
    COMPOSER_HOME={{ composer_home }} composer global {{ item.status }} {{ item.name }} --no-interaction --no-update
  with_items:
    - { status: 'require', name: 'hirak/prestissimo:@stable' }
    - { status: 'require', name: 'consolidation/cgr:@stable' }
  register: composer_global_result
  changed_when: composer_global_result.rc != 0
  tags: hswong3i.composer

- name: composer global update
  shell: |
    COMPOSER_HOME={{ composer_home }} composer global update --no-interaction
  register: composer_global_update_result
  changed_when: "'Nothing to install or update' not in composer_global_update_result.stderr"
  tags: hswong3i.composer

- name: cgr require
  shell: |
    COMPOSER_HOME={{ composer_home }} {{ composer_home }}/vendor/bin/cgr require {{ item.name }} {{ item.version | default('@stable') }} --stability {{ item.stability | default('stable') }}
  with_items: "{{ composer_global }}"
  register: cgr_require_result
  changed_when: cgr_require_result.rc != 0
  tags: hswong3i.composer

- name: cgr update
  shell: |
    COMPOSER_HOME={{ composer_home }} {{ composer_home }}/vendor/bin/cgr update
  register: cgr_update_result
  changed_when: "'Package operations:' in cgr_update_result.stderr"
  tags: hswong3i.composer
